# Generated by Django 4.2.4 on 2023-08-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WantedBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('writer', models.CharField(max_length=30, verbose_name='작성자')),
                ('title', models.CharField(max_length=30, verbose_name='제목')),
                ('contents', models.TextField(max_length=300, verbose_name='내용')),
                ('job_type', models.CharField(choices=[('DESIGN', 'DESIGN'), ('PM', 'PM'), ('FRONTEND', 'FRONTEND'), ('BACKEND', 'BACKEND'), ('MARKETING', 'MARKETING')], max_length=15, verbose_name='직업 종류')),
                ('link', models.URLField(blank=True, null=True, verbose_name='링크')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
