# Generated by Django 4.2.4 on 2023-08-07 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_wantedboard_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wantedboard',
            name='job_type',
            field=models.CharField(choices=[('디자인', 'Design'), ('기획', 'Pm'), ('프론트엔드', 'Frontend'), ('백엔드', 'Backend'), ('마케팅', 'Marketing'), ('기타', 'Etc')], max_length=15, verbose_name='직업 종류'),
        ),
    ]
