# Generated by Django 4.2.4 on 2023-08-07 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_alter_wantedboard_job_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wantedboard',
            old_name='Links',
            new_name='links',
        ),
        migrations.AlterField(
            model_name='wantedboard',
            name='file',
            field=models.FileField(blank=True, upload_to='wanted_board_files', verbose_name='첨부 파일'),
        ),
        migrations.AlterField(
            model_name='wantedboard',
            name='job_type',
            field=models.CharField(choices=[('Design', '디자인'), ('PM', '기획'), ('Frontend', '프론트엔드'), ('Backend', '백엔드'), ('Marketing', '마케팅')], max_length=15, verbose_name='직업 종류'),
        ),
    ]
