# Generated by Django 4.2.4 on 2023-08-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_rename_links_wantedboard_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wantedboard',
            name='links',
            field=models.URLField(blank=True, verbose_name='링크'),
        ),
    ]
