# Generated by Django 4.2.4 on 2023-08-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_alter_wantedboard_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wantedboard',
            name='writer',
            field=models.CharField(max_length=30, verbose_name='작성자'),
        ),
    ]
