# Generated by Django 4.2.4 on 2023-08-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_alter_wantedboard_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wantedboard',
            name='file',
            field=models.URLField(blank=True, default='', verbose_name='첨부 파일'),
        ),
    ]
