# Generated by Django 4.2.4 on 2023-08-07 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_alter_wantedboard_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wantedboard',
            name='file',
        ),
    ]
